site_name: Alexandre Alves' CV
site_url: https://almacoal.net
copyright: almacoal &copy; 2025
nav:
- Summary: index.md
- Current Work: current.md
- Experience:
  - experience.md
  - AI Cloud Engineer: docs/experience/2503-ai-cloud-engineer.md
- Education: education.md
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  palette:
    scheme: slate
    primary: black
    accent: amber
  font:
    text: Atkinson Hyperlegible Next
    code: Atkinson Hyperlegible Mono
  features:
  - toc.integrate
  - navigation.indexes
  - navigation.path
  - navigation.prune
  - navigation.sections
  custom_dir: overrides
extra_css:
- stylesheets/extra.css
hooks:
- hooks/timespans.py
markdown_extensions:
- attr_list
- md_in_html
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
