site_name: Alexandre Alves' CV
site_url: https://almacoal.net
copyright: almacoal &copy; 2025
nav:
- Introduction: index.md
- Experience:
  - experience/index.md
  - Current Role: experience/2503-ai-cloud-architect.md
  - Employers: experience/employers/index.md
  - Skills: skills.md
- Education: education.md
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  palette:
    scheme: slate
    primary: black
    accent: amber
  font:
    text: Atkinson Hyperlegible Next
    code: Atkinson Hyperlegible Code
  features:
  - navigation.expand
  - navigation.indexes
  - navigation.instant
  - navigation.instant.progress
  - navigation.path # Breadcrumbing for sponsors only
  - navigation.prune
  - navigation.sections
  - navigation.tracking
  - toc.follow
  - toc.integrate
  custom_dir: overrides
extra_css:
- stylesheets/extra.css
- stylesheets/neoteroi-mkdocs.css
hooks:
- hooks/timespans.py
markdown_extensions:
- attr_list
- md_in_html
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- neoteroi.projects
plugins:
  - tags
